# Generated by Django 4.2.13 on 2024-07-08 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('AM', 'MAÑANA'), ('PM', 'TARDE'), ('MM', 'NOCHE')], max_length=2)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.FloatField()),
                ('hora_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.combustible')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='combustible',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planta'),
        ),
    ]
