# Generated by Django 4.2.13 on 2024-07-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='codigo_combustible',
            field=models.CharField(choices=[('G93', 'GASOLINA93'), ('G95', 'GASOLINA95'), ('G97', 'GASOLINA97'), ('DIE', 'DIESEL_C'), ('DIP', 'DIESEL_AR'), ('JA1', 'JET'), ('AVG', 'AVGAS')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='turno',
            field=models.CharField(choices=[('AM', 'MAÑANA'), ('PM', 'TARDE'), ('MM', 'NOCHE')], max_length=2),
        ),
    ]
