# Generated by Django 4.2.13 on 2024-07-06 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_registro_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registro',
            name='hora_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
